[build]
functions = "netlify/functions"
publish = "public" # if you have other static assets; otherwise can be any folder


[[redirects]]
from = "/"
to = "/.netlify/functions/page"
status = 200
force = true
