[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/"
  to = "/.netlify/functions/render"
  status = 200

[[redirects]]
  from = "/style.css"
  to = "/.netlify/functions/style"
  status = 200

[[redirects]]
  from = "/init.js"
  to = "/.netlify/functions/init"
  status = 200
